### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [roTokyo/roMacSetup#1]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`chklist.md`](https://github.com/roTokyo/roMacSetup/blob/db6efead2a917f50eb469da71544c3773ebad531/chklist.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by roTokyo** [comment]
Thanks!
